name: Deployment

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

permissions:
    contents: write

jobs:
    deploy:
        name: Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Install node
              uses: actions/setup-node@v4
              with: 
                    node-version: 24 

            - name: Install node modules
              run: npm ci

            - name: Create build
              run: npm run build

            - name: Install zip utility
              run: sudo apt update && sudo apt install zip
            
            - name: zip folder
              run: zip extension.zip dist/*

            - name: Create release
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              uses: softprops/action-gh-release@v3
              with:
                files: |
                    extension.zip
                generate_release_notes: true
            