name: Deployment workflow 

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: installation
        run: npm ci

      - name: building
        run: npm run build
